📌 Purpose: ALV report using CL_SALV_TABLE to display pending leave requests.

REPORT ZLEAVE_MGR_PENDING.

TABLES: ZLEAVE_REQUEST.

TYPES: BEGIN OF TY_LEAVE,
         EMPID      TYPE ZLEAVE_REQUEST-EMPID,
         LEAVE_TYPE TYPE ZLEAVE_REQUEST-LEAVE_TYPE,
         START_DATE TYPE ZLEAVE_REQUEST-START_DATE,
         END_DATE   TYPE ZLEAVE_REQUEST-END_DATE,
         STATUS     TYPE ZLEAVE_REQUEST-STATUS,
       END OF TY_LEAVE.

DATA: IT_LEAVE TYPE STANDARD TABLE OF TY_LEAVE,
      WA_LEAVE TYPE TY_LEAVE.

DATA: O_ALV TYPE REF TO CL_SALV_TABLE.

START-OF-SELECTION.

  SELECT EMPID
         LEAVE_TYPE
         START_DATE
         END_DATE
         STATUS
    FROM ZLEAVE_REQUEST
    INTO TABLE IT_LEAVE
    WHERE STATUS = 'PENDING'.

  TRY.
      CL_SALV_TABLE=>FACTORY(
        IMPORTING R_SALV_TABLE = O_ALV
        CHANGING  T_TABLE      = IT_LEAVE ).

      O_ALV->DISPLAY( ).
    CATCH CX_SALV_MSG INTO DATA(ERR).
      MESSAGE ERR->GET_TEXT( ) TYPE 'E'.
  ENDTRY.
