📌 Purpose: Classical report to display leave history from ZLEAVE_REQUEST.

REPORT ZLEAVE_HISTORY.

TABLES: ZLEAVE_REQUEST.

DATA: IT_LEAVE TYPE STANDARD TABLE OF ZLEAVE_REQUEST,
      WA_LEAVE TYPE ZLEAVE_REQUEST.

START-OF-SELECTION.

  SELECT * FROM ZLEAVE_REQUEST INTO TABLE IT_LEAVE.

  LOOP AT IT_LEAVE INTO WA_LEAVE.
    WRITE: / 'EMPID:',        WA_LEAVE-EMPID,
             'LEAVE TYPE:',   WA_LEAVE-LEAVE_TYPE,
             'FROM:',         WA_LEAVE-START_DATE,
             'TO:',           WA_LEAVE-END_DATE,
             'STATUS:',       WA_LEAVE-STATUS.
  ENDLOOP.
