📌 Purpose: Test report to call AMDP class ZCL_AMDP_LEAVE=>GET_SUMMARY.

REPORT ZTEST_AMDP_LEAVE.

DATA: LT_RESULT TYPE ZLEAVE_SUMMARY_TAB.

PARAMETERS: P_EMPID TYPE MANDT.

START-OF-SELECTION.

  CALL METHOD ZCL_AMDP_LEAVE=>GET_SUMMARY
    EXPORTING
      I_EMPID   = P_EMPID
    IMPORTING
      ET_RESULT = LT_RESULT.

  LOOP AT LT_RESULT INTO DATA(WA_RESULT).
    WRITE: / 'EMPID:',       WA_RESULT-EMPID,
             'LEAVE TYPE:',  WA_RESULT-LEAVE_TYPE,
             'TOTAL DAYS:',  WA_RESULT-TOTAL_DAYS.
  ENDLOOP.
