CLASS ZCL_AMDP_LEAVE IMPLEMENTATION.

  METHOD GET_SUMMARY BY DATABASE PROCEDURE
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING ZLEAVE_REQUEST.

    ET_RESULT = 
      SELECT EMP_ID,
             COUNT(*) AS TOTAL_LEAVES,
             SUM(CASE WHEN STATUS = 'APPROVED' THEN 1 ELSE 0 END) AS APPROVED_LEAVES,
             SUM(CASE WHEN STATUS = 'REJECTED' THEN 1 ELSE 0 END) AS REJECTED_LEAVES,
             SUM(CASE WHEN STATUS = 'PENDING'  THEN 1 ELSE 0 END) AS PENDING_LEAVES
        FROM ZLEAVE_REQUEST
       WHERE EMP_ID = :I_EMPID
       GROUP BY EMP_ID;

  ENDMETHOD.

ENDCLASS.
